#services:
#  mysql:
#    image: mysql
#    ports:
#      - "3306:3306"
#    expose:
#      - "3306"
#    environment:
#      - MYSQL_USER=dbUserDev
#      - MYSQL_PASSWORD=ThePassword
#      - MYSQL_DATABASE=dbpublicacoes
#      - MYSQL_ROOT_PASSWORD=root
#    volumes:
#      - "./conf.d:/etc/mysql/conf.d:ro"